from typing import List, Set

import requests


# request api url generated by searching on website for keyword then copying url from export -> API-webview
def get_intein_iprs() -> Set[str]:
    request_intein_entries = requests.get(
        'https://www.ebi.ac.uk/interpro/wwwapi/entry/InterPro/?search=intein&page_size=100'
    ).json()

    intein_iprs: List[str] = [request_intein_entries['results'][i]['metadata']['accession'] for i in
                              range(request_intein_entries['count'])]

    return set(intein_iprs)


def get_transposase_iprs() -> Set[str]:
    request_transposase_entries = requests.get(
        'https://www.ebi.ac.uk/interpro/wwwapi/entry/InterPro/?search=transposase&page_size=100'
    ).json()
    transposase_iprs = [request_transposase_entries['results'][i]['metadata']['accession'] for i in
                        range(request_transposase_entries['count'])]

    return set(transposase_iprs)


def get_homing_endonuclease_iprs() -> Set[str]:
    request_homing_endonuclease_entries = requests.get(
        'https://www.ebi.ac.uk/interpro/wwwapi/entry/InterPro/?search=homing%20endonuclease&page_size=100'
    ).json()
    homing_endonuclease_iprs = [request_homing_endonuclease_entries['results'][i]['metadata']['accession'] for i in
                                range(request_homing_endonuclease_entries['count'])]

    return set(homing_endonuclease_iprs)


# Now have a list of all interpro domains of interest, need to check this against the ipr domains predicted via
# a galaxy interproscan run against a genome

if __name__ == '__main__':
    inteins: List[str] = get_intein_iprs()
    transposases: List[str] = get_transposase_iprs()
    homing_endonucleases: List[str] = get_homing_endonuclease_iprs()

    print(inteins)
# If so, get the position of that domain from the genome (need to figure out how to do this)


# Then map it onto apollo for the user
